name: dart2html
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Aligator <aligator2236@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.7.0
  build_web_compilers: ^2.9.0